# How Tensor Work and How to Initialize it.

Thanks for the [Amazing tutorials](https://www.youtube.com/playlist?list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz) by [Aladdin Persson](https://www.youtube.com/@AladdinPersson)

## PyTorch

In [2]:
import torch

In [13]:
my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]], 
                          dtype=torch.float32,)

In [18]:
print(f'''
    The type of a tensor object is {my_tensor.dtype}
    To check the device you can use "my_tensor.device": {my_tensor.device}
    it will appear like this 
    {my_tensor} 
    when you print it.
    This is the shape of the tensor {my_tensor.shape}
''')


    The type of a tensor object is torch.float32
    To check the device you can use "my_tensor.device": cpu
    it will appear like this 
    tensor([[1., 2., 3.],
        [4., 5., 6.]]) 
    when you print it.
    This is the shape of the tensor torch.Size([2, 3])



In [27]:
# other way to initizalize tensor is by using
empty = torch.empty(size=(3,3)) # empty tensor
zero = torch.zeros(size=(3,3)) # zeros tensor
random = torch.rand(size=(3,3)) # random tensor by default takes between (0, 1)
ones = torch.ones(size=(3,3)) # tensor with one
identity = torch.eye(3) # identity tensor
range = torch.arange(start=0, end=5, step=1) # for creating a range
linspace = torch.linspace(start=0.1, end=1, steps=10) # for creating a value in between
normalDist = torch.empty(size=(3,3)).normal_(mean=0, std=1) # for creating random number with Normal distribution
unifDist = torch.empty(size=(3,3)).uniform_(0, 10) # for creating random number with unifomr distribution
diagonal = torch.diag(torch.ones(3)) # for creating diagonal tensor

# feel free to print anything you want for better understanding
print(empty)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [30]:
# you can also change tensor to other type
tensor = torch.arange(4)
tensorBool = tensor.bool() # create bool value
tensorShort = tensor.short() # create int16
tensorLong = tensor.long() # create int64 (important)
tensorHalf = tensor.half() # creating float16
tensorFloat = tensor.float() # creating float32 (important)
tensordouble = tensor.double() # creating float64

# feel free to print anything you want for better understanding
print(tensor)

tensor([0, 1, 2, 3])


In [31]:
# array to Tensor and vice-versa
import numpy as np

npArray = np.zeros((5,5))
tensor = torch.from_numpy(npArray)
backToNumpy = tensor.numpy() 

In [65]:
# Maths
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# additions
z = x + y
z1 = torch.add(x,y)
z2 = torch.add(x, y, out=torch.empty(3))

# substractions
z = x - y

# division
z = x / y
z1 = torch.div(x, y)

# inplace operations - can be used for optimizing memory and improving performance by applying the the changes directly
t = torch.zeros(3)
t.add_(x)
t += x # note : t = t + x is not inplace operations
t = t + x

# Exponentiation
z = x ** y

# simple comparison
z = x > 2

# matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = x1.mm(x2)

# matrix exponentiation
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)

# element wise multiplication
z = x * y 

# dot product
z = x.dot(y)

# batch matrix multiplication
batch, n, m, p = 32, 10, 20, 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # the dimension will come out as (batch, n, p)

# Tensorflow

In [66]:
import tensorflow as tf

In [69]:
# initializing tensors in tensorflow

x = tf.constant(4, shape=(1,1), dtype=tf.float32)
x = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
x = tf.ones((3,3))
x = tf.zeros((2, 3))
x = tf.eye(3)
x = tf.random.normal((3, 3), mean=0, stddev=1)
x = tf.random.uniform((1,3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [70]:
# converting type need to use cast
x = tf.cast(x, dtype=tf.float64) 
# can also use tf.float(16, 32, 64), tf.int(8, 16, 32, 64), tf.bool

In [84]:
# maths
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

# additions
z = x + y

# substractions
z = x - y

# dividision
z = x / y

# element wise multiplications
z = x * y

# dot product
z = tf.tensordot(x, y, axes=1)

# exponentiation
z = x ** 5

# matrix multiplication
m = tf.constant([[1, 2, 3]])
n = tf.constant([[2, 3, 4],
                [1, 2, 5],
                [6, 6, 6]])
z = tf.matmul(m, n)
# or you can use this
z = m @ n